apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql-container
    image: 294203522159.dkr.ecr.us-east-1.amazonaws.com/akash7dbrepo:akash0.1
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: asingla7#169498219